//! WorksGood↔Pi integration install — the single `ensure-pi-plugin` primitive
//! plus the embedded, version-locked extension build it materializes.
//!
//! This is the implementation of `docs/design-pi-plugin-install.md`. The core
//! idea: the `wg` binary **carries the exact plugin build it is compatible
//! with**, vendored under `worksgood-pi/embedded/` and embedded at compile time
//! (`include_dir!`). There is no PATH/npm skew to reason about, because the
//! bytes the plugin runs from came out of the same binary that will shell back
//! to `wg`.
//!
//! ## One primitive, two modes
//!
//! [`ensure_pi_plugin`] is a pure function of *(the running `wg` binary, the
//! filesystem)*: resolve the canonical plugin build → place it → (Console mode
//! only) write the pi settings entry → verify it loads and its compat version
//! matches → **no-op if already correct, repair if drifted**. It is fast,
//! headless-safe (never prompts), offline-capable, and self-healing.
//!
//! - [`EnsureMode::Hermetic`] — `wg pi-handler` (JIT, pre-spawn). Never touches
//!   `~/.pi`. Returns a [`ResolvedPlugin`] the handler points `pi -e` at.
//! - [`EnsureMode::Console`] — `wg setup` / `wg profile use pi` /
//!   `wg pi-plugin install`. Additionally writes the global
//!   `~/.pi/agent/settings.json` `extensions` entry for the human-pi direction.
//!
//! ## Compat handshake — `WG_PI_PLUGIN_COMPAT_VERSION`
//!
//! Mirrors [`crate::agency::WG_AGENCY_COMPAT_VERSION`]. The Rust const here is
//! the single source of truth; `make embed-worksgood-pi` stamps it into both
//! `worksgood-pi/embedded/version.json` and `worksgood-pi/src/version.ts`, and
//! the extension asserts it against the binary at startup (failing LOUDLY on
//! mismatch with a WorksGood-specific diagnostic).

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use include_dir::{Dir, include_dir};

/// The WorksGood↔Pi wire-compat version. **Single source of truth.**
///
/// Bump whenever the wg↔plugin flag/contract surface changes. Deliberately
/// decoupled from the npm `package.json` version of `@worksgood/pi`,
/// exactly as agency's `1.2.4` is decoupled from any package version. A unit
/// test asserts this equals `worksgood-pi/embedded/version.json`'s `compat`, so
/// the Rust const and the embedded bundle can never silently diverge.
pub const WG_PI_PLUGIN_COMPAT_VERSION: &str = "0.3.0";

/// Canonical and legacy npm identities used by settings migration.
const NPM_PACKAGE: &str = "@worksgood/pi";
const LEGACY_NPM_PACKAGE: &str = "@worksgood/wg-pi-plugin";

/// The committed, curated plugin runtime, embedded into the binary at compile
/// time. Regenerated by `make embed-worksgood-pi`; CI fails if it drifts from a
/// fresh `npm run build` (see `.github/workflows/ci.yml`). Contains
/// `pi-worksgood/`,
/// `host/`, `package.json`, and `version.json` — no `node_modules` (pi supplies
/// the plugin's peer deps at load).
static EMBEDDED_PI_PLUGIN: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/worksgood-pi/embedded");

/// Integrity stamp written **last** after a complete atomic extraction. Its
/// presence proves the version dir is not a half-written cache.
const OK_STAMP: &str = ".wg-ok";

/// Content-identity stamp written at extraction: the BLAKE3 digest of the exact
/// embedded file set this cache was materialized from. Compared against the
/// running binary's [`embedded_digest`] so an embed change that does NOT bump
/// `WG_PI_PLUGIN_COMPAT_VERSION` still forces re-materialization (the
/// six-week-stale-cache failure: `cache_is_correct` used to validate only file
/// *existence* + the compat string, so the stale build was served forever).
const EMBED_DIGEST_STAMP: &str = ".wg-embed-digest";

/// Which lifecycle point is asking. `Console` additionally wires `~/.pi`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnsureMode {
    /// `wg pi-handler` pre-spawn. Materialize the build; never touch `~/.pi`.
    Hermetic,
    /// `wg setup` / `wg profile use pi` / `wg pi-plugin install`. Also write the
    /// global pi `settings.json` `extensions` entry.
    Console,
}

/// Where the resolved plugin bytes came from (§Decision 4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// The live in-repo `worksgood-pi/pi-worksgood` build.
    Dev,
    /// The embedded bundle extracted into the versioned cache (cargo-installed).
    Cache,
    /// An explicit `WG_PI_PLUGIN_DIR` override, used verbatim.
    EnvOverride,
}

/// Health of the populated cache version dir, versus the running binary's
/// embedded build. Reported by `wg pi-plugin status` so a stale cache is
/// visible without manual forensics.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CacheState {
    /// No usable, stamped cache version dir exists for the current compat.
    Missing,
    /// A cache exists but its content no longer matches the binary's embed:
    /// an embed change under an unchanged compat, a stale/partial cache, or
    /// outright corruption.
    Drift,
    /// Cache content digest matches the binary's embed exactly.
    Current,
}

/// The resolved, ready-to-load plugin build.
#[derive(Debug, Clone)]
pub struct ResolvedPlugin {
    /// The version dir (cache) or the dev `worksgood-pi/` root.
    pub root: PathBuf,
    /// `<root>/pi-worksgood/index.js` — the path for `pi -e`. Pi derives the
    /// startup label from the parent directory, so this path is also the public
    /// display-name contract.
    pub dist_entry: PathBuf,
    /// `<root>/host/wg-pi-host.mjs` — the Topology-B Node host.
    pub host_script: PathBuf,
    /// The `WG_PI_PLUGIN_COMPAT_VERSION` this build materialized.
    pub compat: String,
    /// Where the bytes came from.
    pub source: Source,
    /// True only when `<root>/node_modules` is present (the in-repo dev tree).
    /// Topology B (`node` host) needs it to resolve the pi SDK peer deps.
    pub has_node_modules: bool,
    /// True only for the Console call that actually rewrote a legacy
    /// `@worksgood/wg-pi-plugin` package or old managed extension entry.
    pub legacy_settings_migrated: bool,
    /// True only when this Console call accepted a legacy npm install by
    /// retaining its package record with extension loading disabled. Callers
    /// use this to print the one-time, actionable removal notice.
    pub legacy_package_accepted: bool,
    /// Whether this Console call changed `settings.json` at all.
    pub console_settings_changed: bool,
}

// --- cache location (§Decision 3) ---------------------------------------------

/// The wg cache root: `${XDG_CACHE_HOME:-$HOME/.cache}/wg`, honoring
/// `XDG_CACHE_HOME`, falling back to a temp dir for headless/CI safety when
/// neither is set.
pub fn wg_cache_dir() -> PathBuf {
    if let Some(xdg) = std::env::var_os("XDG_CACHE_HOME")
        && !xdg.is_empty()
    {
        return PathBuf::from(xdg).join("wg");
    }
    if let Some(home) = std::env::var_os("HOME")
        && !home.is_empty()
    {
        return PathBuf::from(home).join(".cache").join("wg");
    }
    std::env::temp_dir().join("wg-cache")
}

/// The global pi settings file the Console direction wires:
/// `~/.pi/agent/settings.json`.
fn pi_settings_path(home: &Path) -> PathBuf {
    home.join(".pi").join("agent").join("settings.json")
}

/// `<cache>/worksgood-pi` — the canonical parent of the per-version dirs.
fn pi_plugin_cache_parent(cache_dir: &Path) -> PathBuf {
    cache_dir.join("worksgood-pi")
}

// --- source selection (§Decision 4) -------------------------------------------

/// The compile-time in-repo component root (`$CARGO_MANIFEST_DIR/worksgood-pi`).
fn compile_time_plugin_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("worksgood-pi")
}

/// Does `dir` look like the repo's `worksgood-pi/` component (name guard)?
/// Prevents a
/// `cargo install`ed binary whose baked `CARGO_MANIFEST_DIR` still exists from
/// loading an unrelated tree.
fn is_wg_plugin_repo(dir: &Path) -> bool {
    let pkg = dir.join("package.json");
    let Ok(text) = std::fs::read_to_string(&pkg) else {
        return false;
    };
    serde_json::from_str::<serde_json::Value>(&text)
        .ok()
        .and_then(|v| v.get("name").and_then(|n| n.as_str()).map(str::to_string))
        .as_deref()
        == Some(NPM_PACKAGE)
}

/// True when `path` lives inside a WG-managed (or Claude-managed) git worktree.
/// Such a path is prunable and must never be baked into a globally installed
/// binary as its Dev source (the `cargo install --path .`-from-a-worktree
/// hazard: the baked `CARGO_MANIFEST_DIR` pointed at
/// `/home/bot/wg/.wg-worktrees/agent-NNN`, so `wg pi-plugin install` rewrote
/// `~/.pi/agent/settings.json` at a directory that would later be pruned).
fn is_worktree_path(path: &Path) -> bool {
    let parts: Vec<String> = path
        .components()
        .filter_map(|c| match c {
            std::path::Component::Normal(s) => Some(s.to_string_lossy().to_string()),
            _ => None,
        })
        .collect();
    parts.iter().any(|p| p == ".wg-worktrees")
        || parts
            .windows(2)
            .any(|w| w[0] == ".claude" && w[1] == "worktrees")
}

/// Reject a compile-time plugin tree that is not a legitimate Dev source.
/// Returns a human-readable reason when `plugin_dir` is a valid wg plugin tree
/// **but** lives under a prunable worktree. Returns `None` when the dir is
/// simply not a built wg plugin tree (the caller falls back to Cache silently).
fn worktree_dev_rejection(plugin_dir: &Path) -> Option<String> {
    let dev_present =
        is_wg_plugin_repo(plugin_dir) && plugin_dir.join("pi-worksgood").join("index.js").is_file();
    if !dev_present {
        return None;
    }
    if is_worktree_path(plugin_dir) {
        return Some(format!(
            "compile-time plugin dir {} is inside a WG worktree (.wg-worktrees); \
             a prunable worktree must never be an installed binary's Dev source \
             — falling back to the embedded cache",
            plugin_dir.display()
        ));
    }
    None
}

/// Pick the plugin source by the §Decision-4 precedence:
/// `WG_PI_PLUGIN_DIR` override → in-repo dev tree → embedded→cache.
///
/// `WG_PI_PLUGIN_FORCE_CACHE=1` skips the Dev branch so the embedded→cache
/// (user) path can be exercised from inside a checkout — used by the smoke gate
/// and anyone validating the cargo-installed behavior without leaving the repo.
fn pick_source(plugin_dir: &Path) -> (Source, Option<PathBuf>) {
    let env_override = std::env::var_os("WG_PI_PLUGIN_DIR")
        .filter(|v| !v.is_empty())
        .map(PathBuf::from);
    let force_cache = std::env::var("WG_PI_PLUGIN_FORCE_CACHE")
        .map(|v| !v.is_empty() && v != "0")
        .unwrap_or(false);
    pick_source_with(plugin_dir, force_cache, env_override)
}

/// Environment-free core of [`pick_source`] (unit-testable without env
/// mutation). A worktree Dev path is rejected loudly and falls back to Cache.
fn pick_source_with(
    plugin_dir: &Path,
    force_cache: bool,
    env_override: Option<PathBuf>,
) -> (Source, Option<PathBuf>) {
    if let Some(explicit) = env_override {
        return (Source::EnvOverride, Some(explicit));
    }
    if !force_cache {
        match worktree_dev_rejection(plugin_dir) {
            Some(reason) => eprintln!("warning: WorksGood pi-plugin: {reason}"),
            None if is_wg_plugin_repo(plugin_dir)
                && plugin_dir.join("pi-worksgood").join("index.js").is_file() =>
            {
                return (Source::Dev, Some(plugin_dir.to_path_buf()));
            }
            None => {}
        }
    }
    (Source::Cache, None)
}

// --- embedded extraction + atomic cache materialization (§Decision 3/5) -------

/// Recursively write `dir` into `dest` (paths are relative to the embed root).
fn extract_dir(dir: &Dir<'_>, dest: &Path) -> std::io::Result<()> {
    for file in dir.files() {
        let out = dest.join(file.path());
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(out, file.contents())?;
    }
    for sub in dir.dirs() {
        extract_dir(sub, dest)?;
    }
    Ok(())
}

// --- content-identity digest --------------------------------------------------

/// Deterministic digest over a `(relative-path, bytes)` file set: BLAKE3 over
/// each path + a length-prefixed body, in sorted-path order. Stable across runs
/// and platforms, so the digest the extracting binary writes always equals the
/// digest a later verify computes.
fn digest_files(files: &mut [(String, Vec<u8>)]) -> String {
    files.sort_by(|a, b| a.0.cmp(&b.0));
    let mut hasher = blake3::Hasher::new();
    for (path, contents) in files.iter() {
        hasher.update(path.as_bytes());
        hasher.update(&[0]);
        hasher.update(&(contents.len() as u64).to_le_bytes());
        hasher.update(contents);
    }
    format!("b3:{}", hasher.finalize().to_hex())
}

fn collect_embedded_files(dir: &Dir<'_>, out: &mut Vec<(String, Vec<u8>)>) {
    for file in dir.files() {
        out.push((
            file.path().to_string_lossy().replace('\\', "/"),
            file.contents().to_vec(),
        ));
    }
    for sub in dir.dirs() {
        collect_embedded_files(sub, out);
    }
}

/// The content digest of the exact file set this binary embeds. Computed once.
fn embedded_digest() -> &'static str {
    static DIGEST: std::sync::OnceLock<String> = std::sync::OnceLock::new();
    DIGEST.get_or_init(|| {
        let mut files = Vec::new();
        collect_embedded_files(&EMBEDDED_PI_PLUGIN, &mut files);
        digest_files(&mut files)
    })
}

/// Recompute the content digest of an extracted cache dir, ignoring the two
/// integrity stamps (which are not part of the embedded set). `None` when the
/// dir cannot be walked.
fn cache_content_digest(version_dir: &Path) -> Option<String> {
    let mut files = Vec::new();
    for entry in walkdir::WalkDir::new(version_dir).sort_by_file_name() {
        let entry = entry.ok()?;
        if !entry.file_type().is_file() {
            continue;
        }
        let name = entry.file_name().to_string_lossy();
        if name == OK_STAMP || name == EMBED_DIGEST_STAMP {
            continue;
        }
        let rel = entry
            .path()
            .strip_prefix(version_dir)
            .ok()?
            .to_string_lossy()
            .replace('\\', "/");
        files.push((rel, std::fs::read(entry.path()).ok()?));
    }
    Some(digest_files(&mut files))
}

fn read_digest_stamp(version_dir: &Path) -> Option<String> {
    let text = std::fs::read_to_string(version_dir.join(EMBED_DIGEST_STAMP)).ok()?;
    let text = text.trim().to_string();
    (!text.is_empty()).then_some(text)
}

/// The §Decision-5 "already correct" predicate for a cache version dir `T`:
/// present (extension + host) **and** version-matched **and** intact (`.wg-ok`)
/// **and** content-identical to the running binary's embed — both by the
/// extraction-time digest stamp and by recomputing the content digest, so a
/// changed embed (same compat), a half-written cache, or corruption all force
/// re-materialization.
fn cache_is_correct(version_dir: &Path) -> bool {
    if !version_dir.join("pi-worksgood").join("index.js").is_file() {
        return false;
    }
    if !version_dir.join("host").join("wg-pi-host.mjs").is_file() {
        return false;
    }
    if !version_dir.join(OK_STAMP).is_file() {
        return false;
    }
    if read_version_json(&version_dir.join("version.json")).as_deref()
        != Some(WG_PI_PLUGIN_COMPAT_VERSION)
    {
        return false;
    }
    let expected = embedded_digest();
    if read_digest_stamp(version_dir).as_deref() != Some(expected) {
        return false;
    }
    cache_content_digest(version_dir).as_deref() == Some(expected)
}

/// Classify the populated cache dir for `wg pi-plugin status`.
fn cache_state(version_dir: &Path) -> CacheState {
    if !version_dir.join("pi-worksgood").join("index.js").is_file()
        || !version_dir.join(OK_STAMP).is_file()
    {
        return CacheState::Missing;
    }
    if cache_is_correct(version_dir) {
        CacheState::Current
    } else {
        CacheState::Drift
    }
}

/// Read the `compat` field out of a `version.json`.
fn read_version_json(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    serde_json::from_str::<serde_json::Value>(&text)
        .ok()?
        .get("compat")
        .and_then(|c| c.as_str())
        .map(str::to_string)
}

/// Best-effort GC of sibling version dirs (and stale `.tmp-*`) under
/// `<cache>/worksgood-pi/` whose name ≠ the current compat version. Never fatal.
fn gc_sibling_versions(parent: &Path, keep: &str) {
    let Ok(entries) = std::fs::read_dir(parent) else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name == keep {
            continue;
        }
        // Remove other version dirs and any leftover atomic-extract temps.
        if name.starts_with('.') && !name.contains("tmp-") {
            continue; // leave unrelated dotfiles alone
        }
        let path = entry.path();
        if path.is_dir() {
            let _ = std::fs::remove_dir_all(&path);
        } else {
            let _ = std::fs::remove_file(&path);
        }
    }
}

/// Make `<parent>/<compat>/` correct, extracting the embedded bundle atomically
/// if it is absent / drifted / half-written. Returns the version dir. Idempotent:
/// a second call on a correct cache is a pure no-op (a few `stat`s).
fn materialize_cache(parent: &Path) -> Result<PathBuf> {
    let version_dir = parent.join(WG_PI_PLUGIN_COMPAT_VERSION);
    if cache_is_correct(&version_dir) {
        gc_sibling_versions(parent, WG_PI_PLUGIN_COMPAT_VERSION);
        return Ok(version_dir);
    }

    std::fs::create_dir_all(parent)
        .with_context(|| format!("create WorksGood Pi cache parent {:?}", parent))?;

    // Atomic extraction: build a sibling temp dir, then rename into place. A
    // crash mid-extract leaves a `.tmp-*` (GC'd) and no `.wg-ok` in the live
    // dir, so the next ensure re-extracts.
    let tmp = parent.join(format!(
        ".{}.tmp-{}",
        WG_PI_PLUGIN_COMPAT_VERSION,
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).with_context(|| format!("create extract temp {:?}", tmp))?;
    extract_dir(&EMBEDDED_PI_PLUGIN, &tmp).context("extract embedded WorksGood Pi bundle")?;
    // `version.json` is part of the embed; assert it landed and matches.
    let extracted = read_version_json(&tmp.join("version.json"));
    if extracted.as_deref() != Some(WG_PI_PLUGIN_COMPAT_VERSION) {
        let _ = std::fs::remove_dir_all(&tmp);
        anyhow::bail!(
            "embedded WorksGood Pi version.json ({:?}) does not match WG_PI_PLUGIN_COMPAT_VERSION ({}) \
             — the binary's embed is corrupt; re-run `make embed-worksgood-pi`",
            extracted,
            WG_PI_PLUGIN_COMPAT_VERSION
        );
    }
    // Content-identity stamp (the embedded file-set digest), then the
    // integrity stamp written LAST, then swap into place.
    let digest = embedded_digest();
    std::fs::write(tmp.join(EMBED_DIGEST_STAMP), format!("{digest}\n"))
        .context("write .wg-embed-digest content stamp")?;
    std::fs::write(tmp.join(OK_STAMP), b"ok\n").context("write .wg-ok integrity stamp")?;
    let _ = std::fs::remove_dir_all(&version_dir);
    std::fs::rename(&tmp, &version_dir)
        .with_context(|| format!("atomic rename {:?} -> {:?}", tmp, version_dir))?;

    gc_sibling_versions(parent, WG_PI_PLUGIN_COMPAT_VERSION);
    Ok(version_dir)
}

// --- Console settings upsert (§Decision 2) ------------------------------------

/// Is `entry` a WorksGood-managed `extensions` entry (canonical or legacy)?
/// Used to replace our own entry idempotently while leaving all unrelated
/// extensions untouched.
fn is_wg_managed_entry(entry: &str, new_entry: &str) -> bool {
    entry == new_entry
        || entry.contains("/wg/pi-plugin/")
        || entry.contains("/wg/worksgood-pi/")
        || entry.ends_with("/pi-plugin/dist/index.js")
        || entry.ends_with("/worksgood-pi/dist/index.js")
        || entry.ends_with("/worksgood-pi/pi-worksgood/index.js")
}

fn is_package_source(source: &str, package_name: &str) -> bool {
    [format!("npm:{package_name}"), package_name.to_string()]
        .iter()
        .any(|prefix| {
            source
                .strip_prefix(prefix)
                .is_some_and(|suffix| suffix.is_empty() || suffix.starts_with('@'))
        })
}

fn is_canonical_package_source(source: &str) -> bool {
    is_package_source(source, NPM_PACKAGE)
}

fn is_legacy_package_source(source: &str) -> bool {
    is_package_source(source, LEGACY_NPM_PACKAGE)
}

fn package_source(package: &serde_json::Value) -> Option<&str> {
    package.as_str().or_else(|| {
        package
            .as_object()
            .and_then(|object| object.get("source"))
            .and_then(serde_json::Value::as_str)
    })
}

/// Keep a Pi package record (and therefore its version pin and unrelated
/// filters) while disabling this package's extension resource. The compat-
/// locked managed path is loaded instead, so package and path identities can
/// never register the WorksGood tools twice. String entries become the
/// equivalent object form documented by Pi.
fn disable_package_extension(package: serde_json::Value) -> (serde_json::Value, bool) {
    match package {
        serde_json::Value::String(source) => (
            serde_json::json!({
                "source": source,
                "extensions": []
            }),
            true,
        ),
        serde_json::Value::Object(mut object) => {
            let already_disabled = object
                .get("extensions")
                .and_then(serde_json::Value::as_array)
                .is_some_and(Vec::is_empty);
            if already_disabled {
                (serde_json::Value::Object(object), false)
            } else {
                object.insert("extensions".into(), serde_json::json!([]));
                (serde_json::Value::Object(object), true)
            }
        }
        other => (other, false),
    }
}

fn package_extension_disabled(package: &serde_json::Value) -> bool {
    package
        .as_object()
        .and_then(|object| object.get("extensions"))
        .and_then(serde_json::Value::as_array)
        .is_some_and(Vec::is_empty)
}

#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
struct SettingsUpdate {
    changed: bool,
    legacy_migrated: bool,
    legacy_package_accepted: bool,
}

/// Upsert the wg `extensions` entry in a pi `settings.json`. Returns `true` if
/// the file changed (so callers can report no-op vs wired). Idempotent: a second
/// call with the same `dist_entry` leaves the file byte-identical and returns
/// `false`.
fn upsert_console_settings(settings_path: &Path, dist_entry: &Path) -> Result<SettingsUpdate> {
    let new_entry = dist_entry.to_string_lossy().to_string();

    let mut root: serde_json::Value = match std::fs::read_to_string(settings_path) {
        Ok(text) if !text.trim().is_empty() => serde_json::from_str(&text).with_context(|| {
            format!(
                "parse existing pi settings {:?} (refusing to clobber)",
                settings_path
            )
        })?,
        _ => serde_json::json!({}),
    };
    if !root.is_object() {
        anyhow::bail!(
            "pi settings {:?} is not a JSON object; refusing to overwrite",
            settings_path
        );
    }

    // Pi treats package and path settings as different identities. Preserve
    // package records/version pins, but disable their extension resource and
    // load the binary's compat-locked path exactly once. This also keeps a
    // legacy npm install functional offline: rewriting its source to a new,
    // absent package would otherwise remove the embedded path and load nothing.
    let mut legacy_migrated = false;
    let mut legacy_package_accepted = false;
    if let Some(packages) = root.get_mut("packages").and_then(|p| p.as_array_mut()) {
        for package in packages {
            let source = package_source(package).map(str::to_owned);
            let is_legacy = source.as_deref().is_some_and(is_legacy_package_source);
            let is_worksgood =
                is_legacy || source.as_deref().is_some_and(is_canonical_package_source);
            if !is_worksgood {
                continue;
            }
            let (disabled, changed) = disable_package_extension(std::mem::take(package));
            *package = disabled;
            if is_legacy && changed {
                legacy_migrated = true;
                legacy_package_accepted = true;
            }
        }
    }

    // Preserve every unrelated path entry in order, remove every prior managed
    // path, and append exactly one canonical path.
    let mut kept: Vec<serde_json::Value> = Vec::new();
    if let Some(existing) = root.get("extensions").and_then(|e| e.as_array()) {
        for v in existing {
            match v.as_str() {
                Some(s) if is_wg_managed_entry(s, &new_entry) => {
                    legacy_migrated |= s != new_entry;
                }
                _ => kept.push(v.clone()),
            }
        }
    }
    kept.push(serde_json::Value::String(new_entry));

    let before = std::fs::read_to_string(settings_path).ok();
    root["extensions"] = serde_json::Value::Array(kept);

    let serialized = serde_json::to_string_pretty(&root)? + "\n";
    if before.as_deref() == Some(serialized.as_str()) {
        return Ok(SettingsUpdate {
            changed: false,
            legacy_migrated: false,
            legacy_package_accepted: false,
        });
    }

    if let Some(parent) = settings_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create pi settings dir {:?}", parent))?;
    }
    std::fs::write(settings_path, serialized)
        .with_context(|| format!("write pi settings {:?}", settings_path))?;
    Ok(SettingsUpdate {
        changed: true,
        legacy_migrated,
        legacy_package_accepted,
    })
}

// --- the primitive ------------------------------------------------------------

/// Testable core of [`ensure_pi_plugin`]: explicit source/cache/home so unit
/// tests need no env mutation. `pick` is the resolved `(Source, root override)`;
/// `cache_dir` is the wg cache root; `home` is the `~` for Console wiring.
fn ensure_pi_plugin_at(
    mode: EnsureMode,
    pick: (Source, Option<PathBuf>),
    cache_dir: &Path,
    home: &Path,
) -> Result<ResolvedPlugin> {
    let (source, override_root) = pick;
    let root = match source {
        Source::Cache => materialize_cache(&pi_plugin_cache_parent(cache_dir))?,
        Source::Dev | Source::EnvOverride => override_root
            .clone()
            .context("dev/override source requires a root path")?,
    };

    let dist_entry = root.join("pi-worksgood").join("index.js");
    let host_script = root.join("host").join("wg-pi-host.mjs");
    if !dist_entry.is_file() {
        anyhow::bail!(
            "resolved WorksGood Pi integration is missing {:?} (source={:?}) — \
             run `npm --prefix worksgood-pi run build` (dev) or `wg pi-plugin install`",
            dist_entry,
            source
        );
    }

    // Dev/override compat: prefer a present version.json, else the binary const
    // (the dev tree's built version.js carries the same value by construction;
    // a stale dev build is caught loudly by the plugin's own runtime assertion).
    let compat = read_version_json(&root.join("version.json"))
        .unwrap_or_else(|| WG_PI_PLUGIN_COMPAT_VERSION.to_string());

    let has_node_modules = root.join("node_modules").is_dir();

    let settings_update = if mode == EnsureMode::Console {
        upsert_console_settings(&pi_settings_path(home), &dist_entry)?
    } else {
        SettingsUpdate::default()
    };

    Ok(ResolvedPlugin {
        root,
        dist_entry,
        host_script,
        compat,
        source,
        has_node_modules,
        legacy_settings_migrated: settings_update.legacy_migrated,
        legacy_package_accepted: settings_update.legacy_package_accepted,
        console_settings_changed: settings_update.changed,
    })
}

/// The one idempotent primitive: resolve → place → (Console) wire → verify.
///
/// Reads the live environment (`WG_PI_PLUGIN_DIR`, `XDG_CACHE_HOME`, `HOME`),
/// selects the source (§Decision 4), and delegates to [`ensure_pi_plugin_at`].
/// Headless-safe and non-interactive; never prompts. Running it twice is a pure
/// no-op the second time.
pub fn ensure_pi_plugin(mode: EnsureMode) -> Result<ResolvedPlugin> {
    let pick = pick_source(&compile_time_plugin_dir());
    ensure_pi_plugin_at(mode, pick, &wg_cache_dir(), &home_dir())
}

/// Like [`ensure_pi_plugin`] but FORCES the in-repo dev source
/// (`worksgood-pi/pi-worksgood`), for `wg pi-plugin install --dev`. Errors clearly when run
/// outside a wg checkout or before a `npm run build`.
pub fn ensure_pi_plugin_dev(mode: EnsureMode) -> Result<ResolvedPlugin> {
    let plugin_dir = compile_time_plugin_dir();
    if !is_wg_plugin_repo(&plugin_dir) {
        anyhow::bail!(
            "`--dev` requires an in-repo WorksGood checkout, but {:?} is not the worksgood-pi tree",
            plugin_dir
        );
    }
    if !plugin_dir.join("pi-worksgood").join("index.js").is_file() {
        anyhow::bail!(
            "`--dev` requires a built bundle, but {:?} is missing — run \
             `npm --prefix worksgood-pi run build` first",
            plugin_dir.join("pi-worksgood").join("index.js")
        );
    }
    ensure_pi_plugin_at(
        mode,
        (Source::Dev, Some(plugin_dir)),
        &wg_cache_dir(),
        &home_dir(),
    )
}

/// `~` for Console wiring, falling back to a temp dir when `HOME` is unset.
fn home_dir() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(std::env::temp_dir)
}

/// A read-only snapshot of the install state (for `wg pi-plugin status`). Never
/// mutates the cache or settings — it reports what `ensure-pi-plugin` *would*
/// resolve and whether the console direction is currently wired.
#[derive(Debug, Clone)]
pub struct PluginStatus {
    /// The binary's compat version.
    pub compat: String,
    /// Which source `ensure-pi-plugin` would use right now.
    pub source: Source,
    /// The dist entry that source resolves to.
    pub dist_entry: PathBuf,
    /// The versioned cache dir (whether or not it is populated).
    pub cache_version_dir: PathBuf,
    /// Whether the resolved build is present + version-matched + intact.
    pub ready: bool,
    /// The global pi settings file.
    pub settings_path: PathBuf,
    /// Whether `settings.json` already lists the resolved dist entry.
    pub console_wired: bool,
    /// Content digest of the file set this binary embeds.
    pub embed_digest: String,
    /// Content digest recomputed from the populated cache dir, if any.
    pub cache_digest: Option<String>,
    /// Cache health vs this binary's embed (Missing / Drift / Current).
    pub cache_state: CacheState,
}

/// Read-only resolution for `wg pi-plugin status` / `path`.
pub fn status() -> PluginStatus {
    let pick = pick_source(&compile_time_plugin_dir());
    status_at(pick, &wg_cache_dir(), &home_dir())
}

/// Environment-free core of [`status`] (unit-testable).
fn status_at(pick: (Source, Option<PathBuf>), cache_dir: &Path, home: &Path) -> PluginStatus {
    let (source, override_root) = pick;
    let cache_version_dir = pi_plugin_cache_parent(cache_dir).join(WG_PI_PLUGIN_COMPAT_VERSION);
    let root = match source {
        Source::Cache => cache_version_dir.clone(),
        Source::Dev | Source::EnvOverride => {
            override_root.unwrap_or_else(|| cache_version_dir.clone())
        }
    };
    let dist_entry = root.join("pi-worksgood").join("index.js");
    let cache_state = cache_state(&cache_version_dir);
    let ready = match source {
        Source::Cache => cache_state == CacheState::Current,
        Source::Dev | Source::EnvOverride => dist_entry.is_file(),
    };
    let settings_path = pi_settings_path(home);
    let console_wired = settings_lists_entry(&settings_path, &dist_entry);
    PluginStatus {
        compat: WG_PI_PLUGIN_COMPAT_VERSION.to_string(),
        source,
        dist_entry,
        cache_version_dir: cache_version_dir.clone(),
        ready,
        settings_path,
        console_wired,
        embed_digest: embedded_digest().to_string(),
        cache_digest: cache_content_digest(&cache_version_dir),
        cache_state,
    }
}

/// Whether settings wire exactly one canonical WorksGood integration through
/// the managed path, with any canonical/legacy package copies disabled.
fn settings_lists_entry(settings_path: &Path, dist_entry: &Path) -> bool {
    let Ok(text) = std::fs::read_to_string(settings_path) else {
        return false;
    };
    let want = dist_entry.to_string_lossy();
    serde_json::from_str::<serde_json::Value>(&text)
        .ok()
        .map(|v| {
            let path_count = v
                .get("extensions")
                .and_then(|e| e.as_array())
                .map(|arr| {
                    arr.iter()
                        .filter_map(|x| x.as_str())
                        .filter(|s| *s == want)
                        .count()
                })
                .unwrap_or(0);
            let package_copies_disabled = v
                .get("packages")
                .and_then(|p| p.as_array())
                .map(|packages| {
                    packages
                        .iter()
                        .filter(|package| {
                            package_source(package).is_some_and(|source| {
                                is_canonical_package_source(source)
                                    || is_legacy_package_source(source)
                            })
                        })
                        .all(package_extension_disabled)
                })
                .unwrap_or(true);
            path_count == 1 && package_copies_disabled
        })
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_compat_version_is_semverish_and_nonempty() {
        assert!(!WG_PI_PLUGIN_COMPAT_VERSION.is_empty());
        let parts: Vec<&str> = WG_PI_PLUGIN_COMPAT_VERSION.split('.').collect();
        assert!(
            parts.len() >= 2,
            "expected semver-ish, got {WG_PI_PLUGIN_COMPAT_VERSION:?}"
        );
        assert!(parts[0].chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn test_embedded_version_json_matches_const() {
        // The embedded bundle's version.json compat MUST equal the Rust const —
        // this is the single-source invariant. Reads the committed embed at the
        // compile-time path (the same dir include_dir! embedded).
        let embedded = compile_time_plugin_dir()
            .join("embedded")
            .join("version.json");
        let compat = read_version_json(&embedded)
            .unwrap_or_else(|| panic!("missing/invalid {:?}", embedded));
        assert_eq!(
            compat, WG_PI_PLUGIN_COMPAT_VERSION,
            "embedded/version.json drifted from WG_PI_PLUGIN_COMPAT_VERSION — re-run `make embed-worksgood-pi`"
        );
    }

    #[test]
    fn test_embedded_bundle_has_runtime_files() {
        // The embed must carry the runtime entry + host so a hermetic extract
        // is loadable.
        assert!(
            EMBEDDED_PI_PLUGIN
                .get_file("pi-worksgood/index.js")
                .is_some(),
            "embed missing pi-worksgood/index.js"
        );
        assert!(
            EMBEDDED_PI_PLUGIN.get_file("host/wg-pi-host.mjs").is_some(),
            "embed missing host/wg-pi-host.mjs"
        );
        assert!(
            EMBEDDED_PI_PLUGIN.get_file("version.json").is_some(),
            "embed missing version.json"
        );
    }

    #[test]
    fn test_materialize_cache_extracts_then_is_noop() {
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());

        // First call extracts.
        let v1 = materialize_cache(&parent).unwrap();
        assert!(v1.join("pi-worksgood").join("index.js").is_file());
        assert!(v1.join("host").join("wg-pi-host.mjs").is_file());
        assert!(v1.join(OK_STAMP).is_file());
        assert!(cache_is_correct(&v1));

        // Second call is a verified no-op (same dir, still correct, no rewrite
        // needed — mtime of the stamp is unchanged).
        let stamp = v1.join(OK_STAMP);
        let mtime1 = std::fs::metadata(&stamp).unwrap().modified().unwrap();
        let v2 = materialize_cache(&parent).unwrap();
        assert_eq!(v1, v2);
        let mtime2 = std::fs::metadata(&stamp).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2, "no-op must not rewrite the stamp");
    }

    #[test]
    fn test_corrupted_cache_is_detected_and_repaired() {
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        let v = materialize_cache(&parent).unwrap();

        // Corrupt: truncate the entry and drop the stamp.
        std::fs::write(v.join("pi-worksgood").join("index.js"), b"// corrupted").unwrap();
        std::fs::remove_file(v.join(OK_STAMP)).unwrap();
        assert!(!cache_is_correct(&v), "corruption must be detected");

        // Repair re-materializes the embedded truth.
        let v2 = materialize_cache(&parent).unwrap();
        assert_eq!(v, v2);
        assert!(cache_is_correct(&v2));
        let restored = std::fs::read(v2.join("pi-worksgood").join("index.js")).unwrap();
        assert_ne!(
            restored, b"// corrupted",
            "repair must overwrite corruption"
        );
    }

    #[test]
    fn test_stale_version_dir_is_gced() {
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        std::fs::create_dir_all(parent.join("0.0.1-old")).unwrap();
        std::fs::write(parent.join("0.0.1-old").join("junk"), b"x").unwrap();

        materialize_cache(&parent).unwrap();
        assert!(
            !parent.join("0.0.1-old").exists(),
            "stale sibling version must be GC'd"
        );
        assert!(parent.join(WG_PI_PLUGIN_COMPAT_VERSION).exists());
    }

    #[test]
    fn test_console_mode_wires_settings_idempotently() {
        let cache = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        let rp = ensure_pi_plugin_at(
            EnsureMode::Console,
            (Source::Cache, None),
            cache.path(),
            home.path(),
        )
        .unwrap();

        let settings = pi_settings_path(home.path());
        let text1 = std::fs::read_to_string(&settings).unwrap();
        let val1: serde_json::Value = serde_json::from_str(&text1).unwrap();
        let exts = val1["extensions"].as_array().unwrap();
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].as_str().unwrap(), rp.dist_entry.to_string_lossy());

        // Re-run: byte-identical (pure no-op the second time).
        let rp2 = ensure_pi_plugin_at(
            EnsureMode::Console,
            (Source::Cache, None),
            cache.path(),
            home.path(),
        )
        .unwrap();
        assert_eq!(rp.dist_entry, rp2.dist_entry);
        let text2 = std::fs::read_to_string(&settings).unwrap();
        assert_eq!(text1, text2, "second Console run must be byte-identical");
    }

    #[test]
    fn test_console_settings_preserves_user_entries_and_replaces_stale_wg() {
        let home = TempDir::new().unwrap();
        let settings = pi_settings_path(home.path());
        std::fs::create_dir_all(settings.parent().unwrap()).unwrap();
        // A user extension + a STALE wg cache entry from an older version.
        std::fs::write(
            &settings,
            serde_json::to_string_pretty(&serde_json::json!({
                "packages": ["npm:pi-web-access@1.0.0"],
                "extensions": [
                    "/home/u/my-ext/index.ts",
                    "/home/u/.cache/wg/pi-plugin/0.0.1/dist/index.js"
                ]
            }))
            .unwrap(),
        )
        .unwrap();

        let new_entry = PathBuf::from("/home/u/.cache/wg/worksgood-pi/0.2.0/pi-worksgood/index.js");
        let update = upsert_console_settings(&settings, &new_entry).unwrap();
        assert!(update.changed);
        assert!(update.legacy_migrated);
        assert!(!update.legacy_package_accepted);

        let val: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        let exts: Vec<&str> = val["extensions"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        // User entry preserved; stale wg entry replaced by the new one; packages intact.
        assert_eq!(
            exts,
            vec![
                "/home/u/my-ext/index.ts",
                "/home/u/.cache/wg/worksgood-pi/0.2.0/pi-worksgood/index.js"
            ]
        );
        assert_eq!(
            val["packages"][0].as_str().unwrap(),
            "npm:pi-web-access@1.0.0"
        );

        // Idempotent: a second upsert with the same entry is a no-op.
        assert!(
            !upsert_console_settings(&settings, &new_entry)
                .unwrap()
                .changed
        );
    }

    #[test]
    fn test_hermetic_mode_never_touches_pi_home() {
        let cache = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        let rp = ensure_pi_plugin_at(
            EnsureMode::Hermetic,
            (Source::Cache, None),
            cache.path(),
            home.path(),
        )
        .unwrap();
        assert_eq!(rp.source, Source::Cache);
        assert!(rp.dist_entry.is_file());
        assert_eq!(rp.compat, WG_PI_PLUGIN_COMPAT_VERSION);
        // Hermetic must NOT have written ~/.pi.
        assert!(
            !home.path().join(".pi").exists(),
            "Hermetic mode must never touch ~/.pi"
        );
    }

    #[test]
    fn test_is_wg_managed_entry() {
        let new = "/c/wg/worksgood-pi/0.2.0/pi-worksgood/index.js";
        assert!(is_wg_managed_entry(new, new));
        assert!(is_wg_managed_entry(
            "/c/wg/pi-plugin/0.0.9/dist/index.js",
            new
        ));
        assert!(is_wg_managed_entry("/repo/pi-plugin/dist/index.js", new));
        assert!(is_wg_managed_entry(
            "/repo/worksgood-pi/pi-worksgood/index.js",
            new
        ));
        assert!(!is_wg_managed_entry("/home/u/other/index.ts", new));
    }

    #[test]
    fn test_console_settings_accepts_legacy_npm_install_without_duplicate_loading() {
        let home = TempDir::new().unwrap();
        let settings = pi_settings_path(home.path());
        std::fs::create_dir_all(settings.parent().unwrap()).unwrap();
        std::fs::write(
            &settings,
            serde_json::to_string_pretty(&serde_json::json!({
                "packages": [
                    "npm:@worksgood/wg-pi-plugin@0.1.0",
                    {
                        "source": "npm:pi-web-access@2.0.0",
                        "extensions": []
                    }
                ],
                "extensions": [
                    "/home/u/.cache/wg/pi-plugin/0.1.1/dist/index.js",
                    "/home/u/other/index.ts"
                ]
            }))
            .unwrap(),
        )
        .unwrap();

        let canonical = PathBuf::from("/home/u/.cache/wg/worksgood-pi/0.2.0/pi-worksgood/index.js");
        let update = upsert_console_settings(&settings, &canonical).unwrap();
        assert!(update.changed);
        assert!(update.legacy_migrated);
        assert!(update.legacy_package_accepted);

        let value: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(
            value["packages"][0]["source"],
            "npm:@worksgood/wg-pi-plugin@0.1.0"
        );
        assert_eq!(value["packages"][0]["extensions"], serde_json::json!([]));
        assert_eq!(value["packages"][1]["source"], "npm:pi-web-access@2.0.0");
        assert_eq!(
            value["extensions"],
            serde_json::json!([
                "/home/u/other/index.ts",
                "/home/u/.cache/wg/worksgood-pi/0.2.0/pi-worksgood/index.js"
            ]),
            "legacy package must be disabled while the managed path loads once"
        );
        assert!(settings_lists_entry(&settings, &canonical));

        let second = upsert_console_settings(&settings, &canonical).unwrap();
        assert!(!second.changed);
        assert!(!second.legacy_migrated);
        assert!(!second.legacy_package_accepted);
    }

    #[test]
    fn test_console_settings_disables_legacy_and_canonical_package_copies() {
        let home = TempDir::new().unwrap();
        let settings = pi_settings_path(home.path());
        std::fs::create_dir_all(settings.parent().unwrap()).unwrap();
        std::fs::write(
            &settings,
            serde_json::to_string_pretty(&serde_json::json!({
                "packages": [
                    {
                        "source": "npm:@worksgood/wg-pi-plugin@0.1.0",
                        "autoload": false,
                        "extensions": ["pi-worksgood/index.js"]
                    },
                    "npm:@worksgood/pi@0.1.0"
                ],
                "extensions": [
                    "/home/u/.cache/wg/pi-plugin/0.1.1/dist/index.js"
                ]
            }))
            .unwrap(),
        )
        .unwrap();

        let canonical = PathBuf::from("/home/u/.cache/wg/worksgood-pi/0.2.0/pi-worksgood/index.js");
        let update = upsert_console_settings(&settings, &canonical).unwrap();
        assert!(update.changed);
        assert!(update.legacy_migrated);
        assert!(update.legacy_package_accepted);

        let value: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        assert_eq!(value["packages"].as_array().unwrap().len(), 2);
        assert_eq!(
            value["packages"][0]["source"],
            "npm:@worksgood/wg-pi-plugin@0.1.0"
        );
        assert_eq!(value["packages"][0]["autoload"], false);
        assert_eq!(value["packages"][0]["extensions"], serde_json::json!([]));
        assert_eq!(value["packages"][1]["source"], "npm:@worksgood/pi@0.1.0");
        assert_eq!(value["packages"][1]["extensions"], serde_json::json!([]));
        assert_eq!(
            value["extensions"],
            serde_json::json!(["/home/u/.cache/wg/worksgood-pi/0.2.0/pi-worksgood/index.js"])
        );
        assert!(settings_lists_entry(&settings, &canonical));
    }

    // --- embed-digest / cache-drift regression (fix-plugin-cache) -----------

    #[test]
    fn test_materialize_cache_carries_shipped_features_and_digest_stamp() {
        // A real re-extract must land EVERY embedded file, including the ones
        // whose absence defined the six-week-stale-cache incident: the
        // completion wakeups (completion-watcher.js) and the VizView panel
        // (viz-panel.js).
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        let v = materialize_cache(&parent).unwrap();

        for shipped in [
            "pi-worksgood/completion-watcher.js",
            "pi-worksgood/viz-panel.js",
            "pi-worksgood/index.js",
            "host/wg-pi-host.mjs",
        ] {
            assert!(
                v.join(shipped).is_file(),
                "re-extracted cache missing shipped file {shipped}"
            );
        }
        assert!(v.join(EMBED_DIGEST_STAMP).is_file());
        assert_eq!(
            std::fs::read_to_string(v.join(EMBED_DIGEST_STAMP))
                .unwrap()
                .trim(),
            embedded_digest()
        );
        assert_eq!(cache_content_digest(&v).as_deref(), Some(embedded_digest()));
        assert_eq!(cache_state(&v), CacheState::Current);
    }

    #[test]
    fn test_embed_digest_mismatch_forces_reextraction() {
        // Simulate a changed embed under an UNCHANGED compat version: the cache
        // stamp no longer matches the binary's embedded digest. The stale cache
        // must be rejected even though index.js/host/version.json/.wg-ok are all
        // present and version-matched — this is exactly the bug that served a
        // six-week-old build forever.
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        let v = materialize_cache(&parent).unwrap();
        std::fs::write(v.join(EMBED_DIGEST_STAMP), b"b3:0000000000stale\n").unwrap();
        assert!(
            !cache_is_correct(&v),
            "stale digest stamp must invalidate the cache"
        );
        assert_eq!(cache_state(&v), CacheState::Drift);

        let v2 = materialize_cache(&parent).unwrap();
        assert!(cache_is_correct(&v2));
        assert_eq!(
            std::fs::read_to_string(v2.join(EMBED_DIGEST_STAMP))
                .unwrap()
                .trim(),
            embedded_digest()
        );

        // A legacy cache written before the digest stamp existed (no stamp at
        // all) is also drift, not "correct".
        std::fs::remove_file(v2.join(EMBED_DIGEST_STAMP)).unwrap();
        assert!(!cache_is_correct(&v2));
        assert_eq!(cache_state(&v2), CacheState::Drift);
    }

    #[test]
    fn test_missing_embedded_file_forces_reextraction() {
        // Content identity, not just index.js + host presence: a stale cache
        // that lost a shipped runtime file (e.g. completion-watcher.js) but kept
        // index.js, .wg-ok and a matching compat must be repaired.
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        let v = materialize_cache(&parent).unwrap();
        std::fs::remove_file(v.join("pi-worksgood").join("completion-watcher.js")).unwrap();
        assert!(
            !cache_is_correct(&v),
            "a missing shipped file must invalidate the cache"
        );

        let v2 = materialize_cache(&parent).unwrap();
        assert!(
            v2.join("pi-worksgood")
                .join("completion-watcher.js")
                .is_file()
        );
        assert!(cache_is_correct(&v2));
    }

    #[test]
    fn test_worktree_dev_source_is_rejected_in_favor_of_cache() {
        // A `cargo install --path .` run from a WG worktree bakes
        // CARGO_MANIFEST_DIR=<repo>/.wg-worktrees/agent-NNN. That prunable path
        // must never be used as the installed binary's Dev source.
        let tmp = TempDir::new().unwrap();
        let wt = tmp
            .path()
            .join(".wg-worktrees")
            .join("agent-144")
            .join("worksgood-pi");
        std::fs::create_dir_all(wt.join("pi-worksgood")).unwrap();
        std::fs::write(wt.join("package.json"), r#"{"name":"@worksgood/pi"}"#).unwrap();
        std::fs::write(wt.join("pi-worksgood").join("index.js"), b"// dev").unwrap();

        assert!(is_worktree_path(&wt));
        let reason = worktree_dev_rejection(&wt).expect("worktree dev tree must be rejected");
        assert!(
            reason.contains(".wg-worktrees") && reason.contains("falling back"),
            "rejection reason must name the worktree + fallback: {reason}"
        );

        let (source, root) = pick_source_with(&wt, false, None);
        assert_eq!(
            source,
            Source::Cache,
            "worktree path must fall back to Cache"
        );
        assert!(root.is_none());
    }

    #[test]
    fn test_non_worktree_dev_source_remains_eligible() {
        let tmp = TempDir::new().unwrap();
        let repo = tmp.path().join("worksgood-pi");
        std::fs::create_dir_all(repo.join("pi-worksgood")).unwrap();
        std::fs::write(repo.join("package.json"), r#"{"name":"@worksgood/pi"}"#).unwrap();
        std::fs::write(repo.join("pi-worksgood").join("index.js"), b"// dev").unwrap();

        assert!(!is_worktree_path(&repo));
        assert!(worktree_dev_rejection(&repo).is_none());
        let (source, root) = pick_source_with(&repo, false, None);
        assert_eq!(source, Source::Dev);
        assert_eq!(root.as_deref(), Some(repo.as_path()));
    }

    #[test]
    fn test_status_reports_cache_missing_drift_and_current() {
        let cache = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();

        // No cache yet.
        let s = status_at((Source::Cache, None), cache.path(), home.path());
        assert_eq!(s.cache_state, CacheState::Missing);
        assert!(!s.ready);
        assert_eq!(s.embed_digest, embedded_digest());
        assert!(s.cache_digest.is_none());

        // Populated + matching.
        let parent = pi_plugin_cache_parent(cache.path());
        let v = materialize_cache(&parent).unwrap();
        let s = status_at((Source::Cache, None), cache.path(), home.path());
        assert_eq!(s.cache_state, CacheState::Current);
        assert!(s.ready);
        assert_eq!(s.cache_digest.as_deref(), Some(embedded_digest()));

        // The six-week-stale cache: content no longer matches the binary embed.
        std::fs::write(v.join(EMBED_DIGEST_STAMP), b"b3:stale-six-weeks\n").unwrap();
        let s = status_at((Source::Cache, None), cache.path(), home.path());
        assert_eq!(s.cache_state, CacheState::Drift);
        assert!(!s.ready, "a drifted cache must not report build ready: yes");
    }

    #[test]
    fn test_status_surfaces_cache_drift_even_for_dev_source() {
        // The resolved Dev build can be present while the embedded cache is
        // stale; status must still surface the drift (the live incident showed
        // `source: EnvOverride` + `build ready: yes` with a six-week-stale
        // cache).
        let cache = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(cache.path());
        let v = materialize_cache(&parent).unwrap();
        std::fs::write(v.join(EMBED_DIGEST_STAMP), b"b3:stale\n").unwrap();

        let dev_root = TempDir::new().unwrap();
        std::fs::create_dir_all(dev_root.path().join("pi-worksgood")).unwrap();
        std::fs::write(
            dev_root.path().join("pi-worksgood").join("index.js"),
            b"// dev",
        )
        .unwrap();
        let s = status_at(
            (Source::Dev, Some(dev_root.path().to_path_buf())),
            cache.path(),
            home.path(),
        );
        assert_eq!(s.source, Source::Dev);
        assert!(s.ready, "the resolved dev entry is present");
        assert_eq!(
            s.cache_state,
            CacheState::Drift,
            "dev source must not mask a stale embedded cache"
        );
    }
}
