//! `wg`↔`pi` plugin install — the single `ensure-pi-plugin` primitive plus the
//! embedded, version-locked plugin build it materializes.
//!
//! This is the implementation of `docs/design-pi-plugin-install.md`. The core
//! idea: the `wg` binary **carries the exact plugin build it is compatible
//! with**, vendored under `pi-plugin/embedded/` and embedded at compile time
//! (`include_dir!`). There is no PATH/npm skew to reason about, because the
//! bytes the plugin runs from came out of the same binary that will shell back
//! to `wg`.
//!
//! ## One primitive, two modes
//!
//! [`ensure_pi_plugin`] is a pure function of *(the running `wg` binary, the
//! filesystem)*: resolve the canonical plugin build → place it → (Console mode
//! only) write the pi settings entry → verify it loads and its compat version
//! matches → **no-op if already correct, repair if drifted**. It is fast,
//! headless-safe (never prompts), offline-capable, and self-healing.
//!
//! - [`EnsureMode::Hermetic`] — `wg pi-handler` (JIT, pre-spawn). Never touches
//!   `~/.pi`. Returns a [`ResolvedPlugin`] the handler points `pi -e` at.
//! - [`EnsureMode::Console`] — `wg setup` / `wg profile use pi` /
//!   `wg pi-plugin install`. Additionally writes the global
//!   `~/.pi/agent/settings.json` `extensions` entry for the human-pi direction.
//!
//! ## Compat handshake — `WG_PI_PLUGIN_COMPAT_VERSION`
//!
//! Mirrors [`crate::agency::WG_AGENCY_COMPAT_VERSION`]. The Rust const here is
//! the single source of truth; `make embed-pi-plugin` stamps it into both
//! `pi-plugin/embedded/version.json` and `pi-plugin/src/version.ts`, and the
//! plugin asserts it against the binary at startup (failing LOUDLY on mismatch).

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use include_dir::{Dir, include_dir};

/// The wg↔pi-plugin wire-compat version. **Single source of truth.**
///
/// Bump whenever the wg↔plugin flag/contract surface changes. Deliberately
/// decoupled from the npm `package.json` version of `@worksgood/wg-pi-plugin`,
/// exactly as agency's `1.2.4` is decoupled from any package version. A unit
/// test asserts this equals `pi-plugin/embedded/version.json`'s `compat`, so
/// the Rust const and the embedded bundle can never silently diverge.
pub const WG_PI_PLUGIN_COMPAT_VERSION: &str = "0.1.1";

/// The committed, curated plugin runtime, embedded into the binary at compile
/// time. Regenerated by `make embed-pi-plugin`; CI fails if it drifts from a
/// fresh `npm run build` (see `.github/workflows/ci.yml`). Contains `dist/`,
/// `host/`, `package.json`, and `version.json` — no `node_modules` (pi supplies
/// the plugin's peer deps at load).
static EMBEDDED_PI_PLUGIN: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/pi-plugin/embedded");

/// Integrity stamp written **last** after a complete atomic extraction. Its
/// presence proves the version dir is not a half-written cache.
const OK_STAMP: &str = ".wg-ok";

/// Which lifecycle point is asking. `Console` additionally wires `~/.pi`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum EnsureMode {
    /// `wg pi-handler` pre-spawn. Materialize the build; never touch `~/.pi`.
    Hermetic,
    /// `wg setup` / `wg profile use pi` / `wg pi-plugin install`. Also write the
    /// global pi `settings.json` `extensions` entry.
    Console,
}

/// Where the resolved plugin bytes came from (§Decision 4).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Source {
    /// The live in-repo `pi-plugin/dist` (a real wg checkout, dev inner loop).
    Dev,
    /// The embedded bundle extracted into the versioned cache (cargo-installed).
    Cache,
    /// An explicit `WG_PI_PLUGIN_DIR` override, used verbatim.
    EnvOverride,
}

/// The resolved, ready-to-load plugin build.
#[derive(Debug, Clone)]
pub struct ResolvedPlugin {
    /// The version dir (cache) or the dev `pi-plugin/` root.
    pub root: PathBuf,
    /// `<root>/dist/index.js` — the path for `pi -e`.
    pub dist_entry: PathBuf,
    /// `<root>/host/wg-pi-host.mjs` — the Topology-B Node host.
    pub host_script: PathBuf,
    /// The `WG_PI_PLUGIN_COMPAT_VERSION` this build materialized.
    pub compat: String,
    /// Where the bytes came from.
    pub source: Source,
    /// True only when `<root>/node_modules` is present (the in-repo dev tree).
    /// Topology B (`node` host) needs it to resolve the pi SDK peer deps.
    pub has_node_modules: bool,
}

// --- cache location (§Decision 3) ---------------------------------------------

/// The wg cache root: `${XDG_CACHE_HOME:-$HOME/.cache}/wg`, honoring
/// `XDG_CACHE_HOME`, falling back to a temp dir for headless/CI safety when
/// neither is set.
pub fn wg_cache_dir() -> PathBuf {
    if let Some(xdg) = std::env::var_os("XDG_CACHE_HOME")
        && !xdg.is_empty()
    {
        return PathBuf::from(xdg).join("wg");
    }
    if let Some(home) = std::env::var_os("HOME")
        && !home.is_empty()
    {
        return PathBuf::from(home).join(".cache").join("wg");
    }
    std::env::temp_dir().join("wg-cache")
}

/// The global pi settings file the Console direction wires:
/// `~/.pi/agent/settings.json`.
fn pi_settings_path(home: &Path) -> PathBuf {
    home.join(".pi").join("agent").join("settings.json")
}

/// `<cache>/pi-plugin` — the parent of the per-version dirs.
fn pi_plugin_cache_parent(cache_dir: &Path) -> PathBuf {
    cache_dir.join("pi-plugin")
}

// --- source selection (§Decision 4) -------------------------------------------

/// The compile-time in-repo plugin root (`$CARGO_MANIFEST_DIR/pi-plugin`).
fn compile_time_plugin_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("pi-plugin")
}

/// Does `dir` look like the wg repo's `pi-plugin/` (name guard)? Prevents a
/// `cargo install`ed binary whose baked `CARGO_MANIFEST_DIR` still exists from
/// loading an unrelated tree.
fn is_wg_plugin_repo(dir: &Path) -> bool {
    let pkg = dir.join("package.json");
    let Ok(text) = std::fs::read_to_string(&pkg) else {
        return false;
    };
    serde_json::from_str::<serde_json::Value>(&text)
        .ok()
        .and_then(|v| v.get("name").and_then(|n| n.as_str()).map(str::to_string))
        .as_deref()
        == Some("@worksgood/wg-pi-plugin")
}

/// Pick the plugin source by the §Decision-4 precedence:
/// `WG_PI_PLUGIN_DIR` override → in-repo dev tree → embedded→cache.
///
/// `WG_PI_PLUGIN_FORCE_CACHE=1` skips the Dev branch so the embedded→cache
/// (user) path can be exercised from inside a checkout — used by the smoke gate
/// and anyone validating the cargo-installed behavior without leaving the repo.
fn pick_source(plugin_dir: &Path) -> (Source, Option<PathBuf>) {
    if let Some(explicit) = std::env::var_os("WG_PI_PLUGIN_DIR")
        && !explicit.is_empty()
    {
        return (Source::EnvOverride, Some(PathBuf::from(explicit)));
    }
    let force_cache = std::env::var("WG_PI_PLUGIN_FORCE_CACHE")
        .map(|v| !v.is_empty() && v != "0")
        .unwrap_or(false);
    if !force_cache
        && is_wg_plugin_repo(plugin_dir)
        && plugin_dir.join("dist").join("index.js").is_file()
    {
        return (Source::Dev, Some(plugin_dir.to_path_buf()));
    }
    (Source::Cache, None)
}

// --- embedded extraction + atomic cache materialization (§Decision 3/5) -------

/// Recursively write `dir` into `dest` (paths are relative to the embed root).
fn extract_dir(dir: &Dir<'_>, dest: &Path) -> std::io::Result<()> {
    for file in dir.files() {
        let out = dest.join(file.path());
        if let Some(parent) = out.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(out, file.contents())?;
    }
    for sub in dir.dirs() {
        extract_dir(sub, dest)?;
    }
    Ok(())
}

/// The §Decision-5 "already correct" predicate for a cache version dir `T`:
/// present (dist + host) **and** version-matched **and** intact (`.wg-ok`).
fn cache_is_correct(version_dir: &Path) -> bool {
    if !version_dir.join("dist").join("index.js").is_file() {
        return false;
    }
    if !version_dir.join("host").join("wg-pi-host.mjs").is_file() {
        return false;
    }
    if !version_dir.join(OK_STAMP).is_file() {
        return false;
    }
    read_version_json(&version_dir.join("version.json")).as_deref()
        == Some(WG_PI_PLUGIN_COMPAT_VERSION)
}

/// Read the `compat` field out of a `version.json`.
fn read_version_json(path: &Path) -> Option<String> {
    let text = std::fs::read_to_string(path).ok()?;
    serde_json::from_str::<serde_json::Value>(&text)
        .ok()?
        .get("compat")
        .and_then(|c| c.as_str())
        .map(str::to_string)
}

/// Best-effort GC of sibling version dirs (and stale `.tmp-*`) under
/// `<cache>/pi-plugin/` whose name ≠ the current compat version. Never fatal.
fn gc_sibling_versions(parent: &Path, keep: &str) {
    let Ok(entries) = std::fs::read_dir(parent) else {
        return;
    };
    for entry in entries.flatten() {
        let name = entry.file_name();
        let name = name.to_string_lossy();
        if name == keep {
            continue;
        }
        // Remove other version dirs and any leftover atomic-extract temps.
        if name.starts_with('.') && !name.contains("tmp-") {
            continue; // leave unrelated dotfiles alone
        }
        let path = entry.path();
        if path.is_dir() {
            let _ = std::fs::remove_dir_all(&path);
        } else {
            let _ = std::fs::remove_file(&path);
        }
    }
}

/// Make `<parent>/<compat>/` correct, extracting the embedded bundle atomically
/// if it is absent / drifted / half-written. Returns the version dir. Idempotent:
/// a second call on a correct cache is a pure no-op (a few `stat`s).
fn materialize_cache(parent: &Path) -> Result<PathBuf> {
    let version_dir = parent.join(WG_PI_PLUGIN_COMPAT_VERSION);
    if cache_is_correct(&version_dir) {
        gc_sibling_versions(parent, WG_PI_PLUGIN_COMPAT_VERSION);
        return Ok(version_dir);
    }

    std::fs::create_dir_all(parent)
        .with_context(|| format!("create pi-plugin cache parent {:?}", parent))?;

    // Atomic extraction: build a sibling temp dir, then rename into place. A
    // crash mid-extract leaves a `.tmp-*` (GC'd) and no `.wg-ok` in the live
    // dir, so the next ensure re-extracts.
    let tmp = parent.join(format!(
        ".{}.tmp-{}",
        WG_PI_PLUGIN_COMPAT_VERSION,
        std::process::id()
    ));
    let _ = std::fs::remove_dir_all(&tmp);
    std::fs::create_dir_all(&tmp).with_context(|| format!("create extract temp {:?}", tmp))?;
    extract_dir(&EMBEDDED_PI_PLUGIN, &tmp).context("extract embedded pi-plugin bundle")?;
    // `version.json` is part of the embed; assert it landed and matches.
    let extracted = read_version_json(&tmp.join("version.json"));
    if extracted.as_deref() != Some(WG_PI_PLUGIN_COMPAT_VERSION) {
        let _ = std::fs::remove_dir_all(&tmp);
        anyhow::bail!(
            "embedded pi-plugin version.json ({:?}) does not match WG_PI_PLUGIN_COMPAT_VERSION ({}) \
             — the binary's embed is corrupt; re-run `make embed-pi-plugin`",
            extracted,
            WG_PI_PLUGIN_COMPAT_VERSION
        );
    }
    // Integrity stamp written LAST, then swap into place.
    std::fs::write(tmp.join(OK_STAMP), b"ok\n").context("write .wg-ok integrity stamp")?;
    let _ = std::fs::remove_dir_all(&version_dir);
    std::fs::rename(&tmp, &version_dir)
        .with_context(|| format!("atomic rename {:?} -> {:?}", tmp, version_dir))?;

    gc_sibling_versions(parent, WG_PI_PLUGIN_COMPAT_VERSION);
    Ok(version_dir)
}

// --- Console settings upsert (§Decision 2) ------------------------------------

/// Is `entry` a wg-managed `extensions` entry (a cache version dist or a dev
/// dist)? Used to replace our own entry idempotently while leaving the user's
/// other extensions/packages untouched.
fn is_wg_managed_entry(entry: &str, new_entry: &str) -> bool {
    entry == new_entry
        || entry.contains("/wg/pi-plugin/")
        || entry.ends_with("/pi-plugin/dist/index.js")
}

/// Upsert the wg `extensions` entry in a pi `settings.json`. Returns `true` if
/// the file changed (so callers can report no-op vs wired). Idempotent: a second
/// call with the same `dist_entry` leaves the file byte-identical and returns
/// `false`.
fn upsert_console_settings(settings_path: &Path, dist_entry: &Path) -> Result<bool> {
    let new_entry = dist_entry.to_string_lossy().to_string();

    let mut root: serde_json::Value = match std::fs::read_to_string(settings_path) {
        Ok(text) if !text.trim().is_empty() => serde_json::from_str(&text).with_context(|| {
            format!(
                "parse existing pi settings {:?} (refusing to clobber)",
                settings_path
            )
        })?,
        _ => serde_json::json!({}),
    };
    if !root.is_object() {
        anyhow::bail!(
            "pi settings {:?} is not a JSON object; refusing to overwrite",
            settings_path
        );
    }

    // Preserve every non-wg-managed entry in order, then append ours.
    let mut kept: Vec<serde_json::Value> = Vec::new();
    if let Some(existing) = root.get("extensions").and_then(|e| e.as_array()) {
        for v in existing {
            match v.as_str() {
                Some(s) if is_wg_managed_entry(s, &new_entry) => {}
                _ => kept.push(v.clone()),
            }
        }
    }
    kept.push(serde_json::Value::String(new_entry));

    let before = root.get("extensions").cloned();
    root["extensions"] = serde_json::Value::Array(kept);
    if before.as_ref() == root.get("extensions") {
        return Ok(false); // already wired identically — no write
    }

    if let Some(parent) = settings_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("create pi settings dir {:?}", parent))?;
    }
    let serialized = serde_json::to_string_pretty(&root)? + "\n";
    std::fs::write(settings_path, serialized)
        .with_context(|| format!("write pi settings {:?}", settings_path))?;
    Ok(true)
}

// --- the primitive ------------------------------------------------------------

/// Testable core of [`ensure_pi_plugin`]: explicit source/cache/home so unit
/// tests need no env mutation. `pick` is the resolved `(Source, root override)`;
/// `cache_dir` is the wg cache root; `home` is the `~` for Console wiring.
fn ensure_pi_plugin_at(
    mode: EnsureMode,
    pick: (Source, Option<PathBuf>),
    cache_dir: &Path,
    home: &Path,
) -> Result<ResolvedPlugin> {
    let (source, override_root) = pick;
    let root = match source {
        Source::Cache => materialize_cache(&pi_plugin_cache_parent(cache_dir))?,
        Source::Dev | Source::EnvOverride => override_root
            .clone()
            .context("dev/override source requires a root path")?,
    };

    let dist_entry = root.join("dist").join("index.js");
    let host_script = root.join("host").join("wg-pi-host.mjs");
    if !dist_entry.is_file() {
        anyhow::bail!(
            "resolved pi-plugin is missing {:?} (source={:?}) — \
             run `npm --prefix pi-plugin run build` (dev) or `wg pi-plugin install`",
            dist_entry,
            source
        );
    }

    // Dev/override compat: prefer a present version.json, else the binary const
    // (the dev tree's built version.js carries the same value by construction;
    // a stale dev build is caught loudly by the plugin's own runtime assertion).
    let compat = read_version_json(&root.join("version.json"))
        .unwrap_or_else(|| WG_PI_PLUGIN_COMPAT_VERSION.to_string());

    let has_node_modules = root.join("node_modules").is_dir();

    if mode == EnsureMode::Console {
        upsert_console_settings(&pi_settings_path(home), &dist_entry)?;
    }

    Ok(ResolvedPlugin {
        root,
        dist_entry,
        host_script,
        compat,
        source,
        has_node_modules,
    })
}

/// The one idempotent primitive: resolve → place → (Console) wire → verify.
///
/// Reads the live environment (`WG_PI_PLUGIN_DIR`, `XDG_CACHE_HOME`, `HOME`),
/// selects the source (§Decision 4), and delegates to [`ensure_pi_plugin_at`].
/// Headless-safe and non-interactive; never prompts. Running it twice is a pure
/// no-op the second time.
pub fn ensure_pi_plugin(mode: EnsureMode) -> Result<ResolvedPlugin> {
    let pick = pick_source(&compile_time_plugin_dir());
    ensure_pi_plugin_at(mode, pick, &wg_cache_dir(), &home_dir())
}

/// Like [`ensure_pi_plugin`] but FORCES the in-repo dev source
/// (`pi-plugin/dist`), for `wg pi-plugin install --dev`. Errors clearly when run
/// outside a wg checkout or before a `npm run build`.
pub fn ensure_pi_plugin_dev(mode: EnsureMode) -> Result<ResolvedPlugin> {
    let plugin_dir = compile_time_plugin_dir();
    if !is_wg_plugin_repo(&plugin_dir) {
        anyhow::bail!(
            "`--dev` requires an in-repo wg checkout, but {:?} is not the wg pi-plugin tree",
            plugin_dir
        );
    }
    if !plugin_dir.join("dist").join("index.js").is_file() {
        anyhow::bail!(
            "`--dev` requires a built bundle, but {:?} is missing — run \
             `npm --prefix pi-plugin run build` first",
            plugin_dir.join("dist").join("index.js")
        );
    }
    ensure_pi_plugin_at(
        mode,
        (Source::Dev, Some(plugin_dir)),
        &wg_cache_dir(),
        &home_dir(),
    )
}

/// `~` for Console wiring, falling back to a temp dir when `HOME` is unset.
fn home_dir() -> PathBuf {
    std::env::var_os("HOME")
        .map(PathBuf::from)
        .unwrap_or_else(std::env::temp_dir)
}

/// A read-only snapshot of the install state (for `wg pi-plugin status`). Never
/// mutates the cache or settings — it reports what `ensure-pi-plugin` *would*
/// resolve and whether the console direction is currently wired.
#[derive(Debug, Clone)]
pub struct PluginStatus {
    /// The binary's compat version.
    pub compat: String,
    /// Which source `ensure-pi-plugin` would use right now.
    pub source: Source,
    /// The dist entry that source resolves to.
    pub dist_entry: PathBuf,
    /// The versioned cache dir (whether or not it is populated).
    pub cache_version_dir: PathBuf,
    /// Whether the resolved build is present + version-matched + intact.
    pub ready: bool,
    /// The global pi settings file.
    pub settings_path: PathBuf,
    /// Whether `settings.json` already lists the resolved dist entry.
    pub console_wired: bool,
}

/// Read-only resolution for `wg pi-plugin status` / `path`.
pub fn status() -> PluginStatus {
    let (source, override_root) = pick_source(&compile_time_plugin_dir());
    let cache_version_dir =
        pi_plugin_cache_parent(&wg_cache_dir()).join(WG_PI_PLUGIN_COMPAT_VERSION);
    let root = match source {
        Source::Cache => cache_version_dir.clone(),
        Source::Dev | Source::EnvOverride => {
            override_root.unwrap_or_else(|| cache_version_dir.clone())
        }
    };
    let dist_entry = root.join("dist").join("index.js");
    let ready = match source {
        Source::Cache => cache_is_correct(&cache_version_dir),
        Source::Dev | Source::EnvOverride => dist_entry.is_file(),
    };
    let settings_path = pi_settings_path(&home_dir());
    let console_wired = settings_lists_entry(&settings_path, &dist_entry);
    PluginStatus {
        compat: WG_PI_PLUGIN_COMPAT_VERSION.to_string(),
        source,
        dist_entry,
        cache_version_dir,
        ready,
        settings_path,
        console_wired,
    }
}

/// Whether `settings.json`'s `extensions` array already lists `dist_entry`.
fn settings_lists_entry(settings_path: &Path, dist_entry: &Path) -> bool {
    let Ok(text) = std::fs::read_to_string(settings_path) else {
        return false;
    };
    let want = dist_entry.to_string_lossy();
    serde_json::from_str::<serde_json::Value>(&text)
        .ok()
        .and_then(|v| {
            v.get("extensions")
                .and_then(|e| e.as_array())
                .map(|arr| arr.iter().filter_map(|x| x.as_str()).any(|s| s == want))
        })
        .unwrap_or(false)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_compat_version_is_semverish_and_nonempty() {
        assert!(!WG_PI_PLUGIN_COMPAT_VERSION.is_empty());
        let parts: Vec<&str> = WG_PI_PLUGIN_COMPAT_VERSION.split('.').collect();
        assert!(
            parts.len() >= 2,
            "expected semver-ish, got {WG_PI_PLUGIN_COMPAT_VERSION:?}"
        );
        assert!(parts[0].chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn test_embedded_version_json_matches_const() {
        // The embedded bundle's version.json compat MUST equal the Rust const —
        // this is the single-source invariant. Reads the committed embed at the
        // compile-time path (the same dir include_dir! embedded).
        let embedded = compile_time_plugin_dir()
            .join("embedded")
            .join("version.json");
        let compat = read_version_json(&embedded)
            .unwrap_or_else(|| panic!("missing/invalid {:?}", embedded));
        assert_eq!(
            compat, WG_PI_PLUGIN_COMPAT_VERSION,
            "embedded/version.json drifted from WG_PI_PLUGIN_COMPAT_VERSION — re-run `make embed-pi-plugin`"
        );
    }

    #[test]
    fn test_embedded_bundle_has_runtime_files() {
        // The embed must carry the runtime entry + host so a hermetic extract
        // is loadable.
        assert!(
            EMBEDDED_PI_PLUGIN.get_file("dist/index.js").is_some(),
            "embed missing dist/index.js"
        );
        assert!(
            EMBEDDED_PI_PLUGIN.get_file("host/wg-pi-host.mjs").is_some(),
            "embed missing host/wg-pi-host.mjs"
        );
        assert!(
            EMBEDDED_PI_PLUGIN.get_file("version.json").is_some(),
            "embed missing version.json"
        );
    }

    #[test]
    fn test_materialize_cache_extracts_then_is_noop() {
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());

        // First call extracts.
        let v1 = materialize_cache(&parent).unwrap();
        assert!(v1.join("dist").join("index.js").is_file());
        assert!(v1.join("host").join("wg-pi-host.mjs").is_file());
        assert!(v1.join(OK_STAMP).is_file());
        assert!(cache_is_correct(&v1));

        // Second call is a verified no-op (same dir, still correct, no rewrite
        // needed — mtime of the stamp is unchanged).
        let stamp = v1.join(OK_STAMP);
        let mtime1 = std::fs::metadata(&stamp).unwrap().modified().unwrap();
        let v2 = materialize_cache(&parent).unwrap();
        assert_eq!(v1, v2);
        let mtime2 = std::fs::metadata(&stamp).unwrap().modified().unwrap();
        assert_eq!(mtime1, mtime2, "no-op must not rewrite the stamp");
    }

    #[test]
    fn test_corrupted_cache_is_detected_and_repaired() {
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        let v = materialize_cache(&parent).unwrap();

        // Corrupt: truncate the entry and drop the stamp.
        std::fs::write(v.join("dist").join("index.js"), b"// corrupted").unwrap();
        std::fs::remove_file(v.join(OK_STAMP)).unwrap();
        assert!(!cache_is_correct(&v), "corruption must be detected");

        // Repair re-materializes the embedded truth.
        let v2 = materialize_cache(&parent).unwrap();
        assert_eq!(v, v2);
        assert!(cache_is_correct(&v2));
        let restored = std::fs::read(v2.join("dist").join("index.js")).unwrap();
        assert_ne!(
            restored, b"// corrupted",
            "repair must overwrite corruption"
        );
    }

    #[test]
    fn test_stale_version_dir_is_gced() {
        let tmp = TempDir::new().unwrap();
        let parent = pi_plugin_cache_parent(tmp.path());
        std::fs::create_dir_all(parent.join("0.0.1-old")).unwrap();
        std::fs::write(parent.join("0.0.1-old").join("junk"), b"x").unwrap();

        materialize_cache(&parent).unwrap();
        assert!(
            !parent.join("0.0.1-old").exists(),
            "stale sibling version must be GC'd"
        );
        assert!(parent.join(WG_PI_PLUGIN_COMPAT_VERSION).exists());
    }

    #[test]
    fn test_console_mode_wires_settings_idempotently() {
        let cache = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        let rp = ensure_pi_plugin_at(
            EnsureMode::Console,
            (Source::Cache, None),
            cache.path(),
            home.path(),
        )
        .unwrap();

        let settings = pi_settings_path(home.path());
        let text1 = std::fs::read_to_string(&settings).unwrap();
        let val1: serde_json::Value = serde_json::from_str(&text1).unwrap();
        let exts = val1["extensions"].as_array().unwrap();
        assert_eq!(exts.len(), 1);
        assert_eq!(exts[0].as_str().unwrap(), rp.dist_entry.to_string_lossy());

        // Re-run: byte-identical (pure no-op the second time).
        let rp2 = ensure_pi_plugin_at(
            EnsureMode::Console,
            (Source::Cache, None),
            cache.path(),
            home.path(),
        )
        .unwrap();
        assert_eq!(rp.dist_entry, rp2.dist_entry);
        let text2 = std::fs::read_to_string(&settings).unwrap();
        assert_eq!(text1, text2, "second Console run must be byte-identical");
    }

    #[test]
    fn test_console_settings_preserves_user_entries_and_replaces_stale_wg() {
        let home = TempDir::new().unwrap();
        let settings = pi_settings_path(home.path());
        std::fs::create_dir_all(settings.parent().unwrap()).unwrap();
        // A user extension + a STALE wg cache entry from an older version.
        std::fs::write(
            &settings,
            serde_json::to_string_pretty(&serde_json::json!({
                "packages": ["npm:pi-web-access@1.0.0"],
                "extensions": [
                    "/home/u/my-ext/index.ts",
                    "/home/u/.cache/wg/pi-plugin/0.0.1/dist/index.js"
                ]
            }))
            .unwrap(),
        )
        .unwrap();

        let new_entry = PathBuf::from("/home/u/.cache/wg/pi-plugin/0.1.0/dist/index.js");
        let changed = upsert_console_settings(&settings, &new_entry).unwrap();
        assert!(changed);

        let val: serde_json::Value =
            serde_json::from_str(&std::fs::read_to_string(&settings).unwrap()).unwrap();
        let exts: Vec<&str> = val["extensions"]
            .as_array()
            .unwrap()
            .iter()
            .map(|v| v.as_str().unwrap())
            .collect();
        // User entry preserved; stale wg entry replaced by the new one; packages intact.
        assert_eq!(
            exts,
            vec![
                "/home/u/my-ext/index.ts",
                "/home/u/.cache/wg/pi-plugin/0.1.0/dist/index.js"
            ]
        );
        assert_eq!(
            val["packages"][0].as_str().unwrap(),
            "npm:pi-web-access@1.0.0"
        );

        // Idempotent: a second upsert with the same entry is a no-op.
        assert!(!upsert_console_settings(&settings, &new_entry).unwrap());
    }

    #[test]
    fn test_hermetic_mode_never_touches_pi_home() {
        let cache = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        let rp = ensure_pi_plugin_at(
            EnsureMode::Hermetic,
            (Source::Cache, None),
            cache.path(),
            home.path(),
        )
        .unwrap();
        assert_eq!(rp.source, Source::Cache);
        assert!(rp.dist_entry.is_file());
        assert_eq!(rp.compat, WG_PI_PLUGIN_COMPAT_VERSION);
        // Hermetic must NOT have written ~/.pi.
        assert!(
            !home.path().join(".pi").exists(),
            "Hermetic mode must never touch ~/.pi"
        );
    }

    #[test]
    fn test_is_wg_managed_entry() {
        let new = "/c/wg/pi-plugin/0.1.0/dist/index.js";
        assert!(is_wg_managed_entry(new, new));
        assert!(is_wg_managed_entry(
            "/c/wg/pi-plugin/0.0.9/dist/index.js",
            new
        ));
        assert!(is_wg_managed_entry("/repo/pi-plugin/dist/index.js", new));
        assert!(!is_wg_managed_entry("/home/u/other/index.ts", new));
    }
}
